// Generated by CoffeeScript 1.9.3
(function() {
  var WebOmiExt;

  WebOmiExt = function($, parent) {
    parent.consts = (function() {
      var afterWaits, my;
      my = {};
      my.codeMirrorSettings = {
        mode: "text/html",
        lineNumbers: true,
        lineWrapping: true
      };
      afterWaits = [];
      my.afterJquery = function(fn) {
        return afterWaits.push(fn);
      };
      $(function() {
        var fn, i, len, results;
        my.requestCodeMirror = CodeMirror.fromTextArea($("#requestArea")[0], my.codeMirrorSettings);
        my.responseCodeMirror = CodeMirror.fromTextArea($("#responseArea")[0], my.codeMirrorSettings);
        my.odfTree = $('#nodetree');
        my.requestSel = $('.requesttree');
        my.readAllBtn = $('#readall');
        my.odfTree.jstree({
          plugins: ["checkbox"]
        }).on("changed.jstree", function(_, data) {
          return console.log(data.node);
        });
        my.requestSel.jstree({
          core: {
            themes: {
              icons: false
            },
            multiple: false
          }
        }).on("changed.jstree", function(_, data) {
          return console.log(data.node.id);
        });
        my.afterJquery = function(fn) {
          return fn();
        };
        results = [];
        for (i = 0, len = afterWaits.length; i < len; i++) {
          fn = afterWaits[i];
          results.push(fn());
        }
        return results;
      });
      return my;
    })();
    return parent;
  };

  window.WebOmi = WebOmiExt($, window.WebOmi || {});

}).call(this);
