// Generated by CoffeeScript 1.9.3
(function() {
  var constsExt;

  constsExt = function($, parent) {
    var afterWaits, my;
    my = parent.consts = {};
    my.codeMirrorSettings = {
      mode: "text/xml",
      lineNumbers: true,
      lineWrapping: true
    };
    afterWaits = [];
    my.afterJquery = function(fn) {
      return afterWaits.push(fn);
    };
    $(function() {
      var basicInput, fn, i, len, responseCMSettings, results;
      responseCMSettings = $.extend({
        readOnly: true
      }, my.codeMirrorSettings);
      my.requestCodeMirror = CodeMirror.fromTextArea($("#requestArea")[0], my.codeMirrorSettings);
      my.responseCodeMirror = CodeMirror.fromTextArea($("#responseArea")[0], responseCMSettings);
      my.serverUrl = $('#targetService');
      my.odfTreeDom = $('#nodetree');
      my.requestSel = $('.requesttree');
      my.readAllBtn = $('#readall');
      my.sendBtn = $('#send');
      ({
        request: function(reqName) {
          if (currentParams.request == null) {
            return my.loadParams(my.defaults[reqName]);
          } else {

          }
        }
      });
      my.odfTreeDom.jstree({
        plugins: ["checkbox", "types"],
        types: {
          "default": {
            icon: "odf-objects glyphicon glyphicon-tree-deciduous"
          },
          object: {
            icon: "odf-object glyphicon glyphicon-folder-open"
          },
          objects: {
            icon: "odf-objects glyphicon glyphicon-tree-deciduous"
          },
          infoitem: {
            icon: "odf-infoitem glyphicon glyphicon-apple"
          }
        },
        checkbox: {
          three_state: false,
          keep_selected_style: true,
          cascade: "up+undetermined",
          tie_selection: true
        }
      });
      my.odfTree = my.odfTreeDom.jstree();
      my.odfTree.set_type('Objects', 'objects');
      my.requestSel.jstree({
        core: {
          themes: {
            icons: false
          },
          multiple: false
        }
      }).on("changed.jstree", function(e, data) {
        return console.log(data.node.id);
      });
      basicInput = function(selector) {
        return {
          ref: $(selector),
          get: function() {
            return this.ref.val();
          },
          set: function(val) {
            return this.ref.val(val);
          }
        };
      };
      my.ui = {
        ttl: basicInput('#ttl'),
        callback: basicInput('#callback'),
        requestID: basicInput('#requestID'),
        odf: {
          ref: my.odfTreeDom,
          get: function() {
            return my.odfTree.get_selected();
          },
          set: function(vals) {
            var i, len, node, results;
            results = [];
            for (i = 0, len = vals.length; i < len; i++) {
              node = vals[i];
              results.push(my.odfTree.select_node(node));
            }
            return results;
          }
        },
        interval: basicInput('#interval'),
        newest: basicInput('#newest'),
        oldest: basicInput('#oldest'),
        begin: basicInput('#begin'),
        end: basicInput('#end'),
        requestDoc: {
          ref: my.requestCodeMirror,
          get: function() {
            return WebOmi.formLogic.getRequest();
          },
          set: function(val) {
            return WebOmi.formLogic.setRequest(val);
          }
        }
      };
      my.afterJquery = function(fn) {
        return fn();
      };
      results = [];
      for (i = 0, len = afterWaits.length; i < len; i++) {
        fn = afterWaits[i];
        results.push(fn());
      }
      return results;
    });
    return parent;
  };

  window.WebOmi = constsExt($, window.WebOmi || {});

  window.jqesc = function(mySel) {
    return '#' + mySel.replace(/(:|\.|\[|\]|,|\/)/g, "\\$1");
  };

  String.prototype.trim = String.prototype.trim || function() {
    return String(this).replace(/^\s+|\s+$/g, '');
  };

}).call(this);
