// Generated by CoffeeScript 1.9.3
(function() {
  var omiExt;

  omiExt = function(WebOmi) {
    var my;
    my = WebOmi.omi = {};
    my.parseXml = function(responseString) {
      return window.xmlTree = new DOMParser().parseFromString(responseString, 'text/xml');
    };
    my.ns = {
      omi: "omi.xsd",
      odf: "odf.xsd",
      xsi: "http://www.w3.org/2001/XMLSchema-instance",
      xs: "http://www.w3.org/2001/XMLSchema-instance"
    };
    my.nsResolver = function(name) {
      return my.ns[name] || my.ns.odf;
    };
    my.evaluateXPath = function(elem, xpath) {
      var iter, res, results, xpe;
      xpe = elem.ownerDocument || elem;
      iter = xpe.evaluate(xpath, elem, my.nsResolver, 0, null);
      results = [];
      while (res = iter.iterateNext()) {
        results.push(res);
      }
      return results;
    };
    return WebOmi;
  };

  window.WebOmi = omiExt(window.WebOmi || {});

}).call(this);
