// Generated by CoffeeScript 1.9.3
(function() {
  var omiExt;

  omiExt = function(WebOmi) {
    var my, nsResolver;
    my = WebOmi.omi = {};
    my.parseXmlResponse = function(responseString) {
      return window.xmlTree = new DOMParser().parseFromString(responseString, 'text/xml');
    };
    nsResolver = function(name) {
      var ns;
      ns = {
        omi: "omi.xsd",
        odf: "odf.xsd"
      };
      return ns[name] || ns.odf;
    };
    my.evaluateXPath = function(elem, xpath) {
      var iter, res, results, xpe;
      xpe = elem.ownerDocument || elem;
      iter = xpe.evaluate(xpath, elem, nsResolver, 0, null);
      results = [];
      while (res = iter.iterateNext()) {
        results.push(res);
      }
      return results;
    };
    return WebOmi;
  };

  window.WebOmi = omiExt(window.WebOmi || {});

}).call(this);
