// Generated by CoffeeScript 1.9.3
(function() {
  var requestsExt;

  requestsExt = function(WebOmi) {
    var my;
    my = WebOmi.requests = {};
    my.xmls = {
      readAll: "<?xml version=\"1.0\"?>\n<omi:omiEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:omi=\"omi.xsd\"\n    version=\"1.0\" ttl=\"0\">\n  <omi:read msgformat=\"odf\">\n    <omi:msg xmlns=\"odf.xsd\" xsi:schemaLocation=\"odf.xsd odf.xsd\">\n      <Objects></Objects>\n    </omi:msg>\n  </omi:read>\n</omi:omiEnvelope> "
    };
    my.readAll = function(fastForward) {
      WebOmi.consts.requestCodeMirror.setValue(my.xmls.readAll);
      if (fastForward) {
        return WebOmi.formLogic.send();
      }
    };
    return WebOmi;
  };

  window.WebOmi = requestsExt(window.WebOmi || {});

}).call(this);
