// Generated by CoffeeScript 1.9.3
(function() {
  var requestsExt;

  requestsExt = function(WebOmi) {
    var currentParams, my;
    my = WebOmi.requests = {};
    my.xmls = {
      readAll: "<?xml version=\"1.0\"?>\n<omi:omiEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:omi=\"omi.xsd\"\n    version=\"1.0\" ttl=\"0\">\n  <omi:read msgformat=\"odf\">\n    <omi:msg xmlns=\"odf.xsd\" xsi:schemaLocation=\"odf.xsd odf.xsd\">\n      <Objects></Objects>\n    </omi:msg>\n  </omi:read>\n</omi:omiEnvelope>",
      templateMsg: "<?xml version=\"1.0\"?>\n<omi:omiEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:omi=\"omi.xsd\"\n    version=\"1.0\" ttl=\"0\">\n  <omi:read msgformat=\"odf\">\n    <omi:msg xmlns=\"odf.xsd\" xsi:schemaLocation=\"odf.xsd odf.xsd\">\n    </omi:msg>\n  </omi:read>\n</omi:omiEnvelope>\n",
      template: "<?xml version=\"1.0\"?>\n<omi:omiEnvelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:omi=\"omi.xsd\"\n    version=\"1.0\" ttl=\"0\">\n  <omi:read msgformat=\"odf\">\n    <omi:msg xmlns=\"odf.xsd\" xsi:schemaLocation=\"odf.xsd odf.xsd\">\n    </omi:msg>\n  </omi:read>\n</omi:omiEnvelope>\n"
    };
    my.defaults = {};
    my.defaults.empty = function() {
      return {
        name: "empty",
        request: null,
        ttl: 0,
        callback: null,
        requestID: null,
        odf: null,
        interval: null,
        newest: null,
        oldest: null,
        begin: null,
        end: null,
        requestDoc: null,
        msg: true
      };
    };
    my.defaults.readAll = function() {
      return $.extend({}, my.defaults.empty(), {
        name: "readAll",
        request: "read",
        odf: ["Objects"],
        requestDoc: WebOmi.omi.parseXml(my.xmls.readAll)
      });
    };
    my.defaults.read = function() {
      return $.extend({}, my.defaults.empty(), {
        request: "readOnce",
        odf: ["Objects"]
      });
    };
    my.defaults.subscription = function() {
      return $.extend({}, my.defaults.empty(), {
        name: "subscription",
        request: "read",
        interval: 5,
        ttl: 60,
        odf: ["Objects"]
      });
    };
    my.defaults.poll = function() {
      return $.extend({}, my.defaults.empty(), {
        name: "poll",
        request: "read",
        requestID: 1,
        msg: false
      });
    };
    my.defaults.write = function() {
      return $.extend({}, my.defaults.empty(), {
        name: "write",
        request: "write",
        odf: ["Objects"]
      });
    };
    my.defaults.cancel = function() {
      return $.extend({}, my.defaults.empty(), {
        name: "cancel",
        request: "cancel",
        requestID: 1,
        odf: null,
        msg: false
      });
    };
    currentParams = my.defaults.empty();
    my.confirmOverwrite = function(oldVal, newVal) {
      return confirm("You have edited the request manually.\n Do you want to overwrite " + oldVal.toString + " with " + newVal.toString);
    };
    my.removePathFromOdf = function(odfTreeNode, odfObjects) {
      var allOdfElems, elem, i, id, lastOdfElem, len, maybeChild, node, nodeElems, o;
      o = WebOmi.omi;
      nodeElems = $.makeArray(odfTreeNode.parentsUntil("#Objects", "li"));
      nodeElems.reverse();
      nodeElems.push(odfTreeNode);
      lastOdfElem = odfObjects;
      allOdfElems = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = nodeElems.length; i < len; i++) {
          node = nodeElems[i];
          id = $(node).children("a").text();
          maybeChild = o.getOdfChild(id, lastOdfElem);
          if (maybeChild != null) {
            lastOdfElem = maybeChild;
          }
          results.push(maybeChild);
        }
        return results;
      })();
      lastOdfElem.parentElement.removeChild(lastOdfElem);
      allOdfElems.pop();
      allOdfElems.reverse();
      for (i = 0, len = allOdfElems.length; i < len; i++) {
        elem = allOdfElems[i];
        if (!o.hasOdfChildren(elem)) {
          elem.parentElement.removeChild(elem);
        }
      }
      return odfObjects;
    };
    my.addPathToOdf = function(odfTreeNode, odfObjects) {
      var currentOdfNode, i, id, len, maybeChild, node, nodeElems, o, obj, odfDoc;
      o = WebOmi.omi;
      odfDoc = odfObjects.ownerDocument || odfObjects;
      nodeElems = $.makeArray(odfTreeNode.parentsUntil("#Objects", "li"));
      nodeElems.reverse();
      nodeElems.push(odfTreeNode);
      currentOdfNode = odfObjects;
      for (i = 0, len = nodeElems.length; i < len; i++) {
        node = nodeElems[i];
        id = $(node).children("a").text();
        maybeChild = o.getOdfChild(id, currentOdfNode);
        if (maybeChild != null) {
          currentOdfNode = maybeChild;
        } else {
          obj = (function() {
            switch (WebOmi.consts.odfTree.get_type(node)) {
              case "object":
                return o.createOdfObject(odfDoc, id);
              case "infoitem":
                return o.createOdfInfoItem(odfDoc, id);
            }
          })();
          currentOdfNode.appendChild(obj);
          currentOdfNode = obj;
        }
      }
      return odfObjects;
    };
    my.params = {
      request: {
        update: function(reqName) {
          var attr, child, currentReq, doc, i, j, len, len1, newReq, ref, ref1;
          if (currentParams.request == null) {
            return my.forceLoadParams(my.defaults[reqName]());
          } else if (reqName !== currentParams.request) {
            doc = currentParams.requestDoc;
            currentReq = WebOmi.omi.evaluateXPath(doc, "omi:omiEnvelope/*")[0];
            newReq = WebOmi.omi.createOmi(reqName, doc);
            ref = currentReq.attributes;
            for (i = 0, len = ref.length; i < len; i++) {
              attr = ref[i];
              newReq.setAttribute(attr.name, attr.value);
            }
            ref1 = currentReq.childNodes;
            for (j = 0, len1 = ref1.length; j < len1; j++) {
              child = ref1[j];
              newReq.appendChild(child);
            }
            currentReq.parentNode.replaceChild(newReq, currentReq);
            return currentParams.request = reqName;
          }
        }
      },
      ttl: {
        update: function() {}
      },
      callback: {
        update: function() {}
      },
      requestID: {
        update: function() {}
      },
      odf: {
        update: function(paths) {
          var doc, i, j, len, len1, msg, o, obs, obss, odfTreeNode, path;
          o = WebOmi.omi;
          doc = currentParams.requestDoc;
          if ((paths != null) && paths.length > 0) {
            obs = o.createOdfObjects(doc);
            for (i = 0, len = paths.length; i < len; i++) {
              path = paths[i];
              odfTreeNode = $(jqesc(path));
              my.addPathToOdf(odfTreeNode, obs);
            }
            if (currentParams.msg) {
              msg = o.evaluateXPath(currentParams.requestDoc, "//omi:msg")[0];
              msg.appendChild(objects);
            }
          } else {
            obss = WebOmi.omi.evaluateXPath(doc, "//odf:Objects");
            for (j = 0, len1 = obss.length; j < len1; j++) {
              obs = obss[j];
              obs.parentElement.removeChild(obs);
            }
          }
          return currentParams.omi = paths;
        },
        add: function(path) {
          var currentObjectsHead, fl, msg, o, objects, odfTreeNode, req;
          o = WebOmi.omi;
          fl = WebOmi.formLogic;
          odfTreeNode = $(jqesc(path));
          req = currentParams.requestDoc;
          if (req != null) {
            currentObjectsHead = o.evaluateXPath(req, '//odf:Objects')[0];
            if (currentObjectsHead != null) {
              my.addPathToOdf(odfTreeNode, currentObjectsHead);
            } else if (currentParams.msg) {
              objects = o.createOdfObjects(xmlTree);
              my.addPathToOdf(odfTreeNode, objects);
              msg = o.evaluateXPath(req, "//omi:msg")[0];
              if (msg != null) {
                msg.appendChild(objects);
              } else {
                console.log("error msg = " + msg);
              }
            }
          }
          if (currentParams.odf != null) {
            return currentParams.odf.push(path);
          } else {
            return currentParams.odf = [path];
          }
        },
        remove: function(path) {
          var fl, o, odfObjects, odfTreeNode, req;
          o = WebOmi.omi;
          fl = WebOmi.formLogic;
          req = currentParams.requestDoc;
          if (currentParams.msg && (req != null)) {
            odfTreeNode = $(jqesc(path));
            odfObjects = o.evaluateXPath(req, '//odf:Objects')[0];
            if (odfObjects != null) {
              my.removePathFromOdf(odfTreeNode, odfObjects);
            }
          }
          if (currentParams.odf != null) {
            return currentParams.odf.filter(function(p) {
              return p !== path;
            });
          } else {
            return currentParams.odf = [];
          }
        }
      },
      interval: {
        update: function() {}
      },
      newest: {
        update: function() {}
      },
      oldest: {
        update: function() {}
      },
      begin: {
        update: function() {}
      },
      end: {
        update: function() {}
      },
      msg: {
        update: function(hasMsg) {
          var doc, i, len, m, msg, o, requestElem;
          o = WebOmi.omi;
          doc = currentParams.requestDoc;
          if (hasMsg === currentParams.msg) {
            return;
          }
          if (hasMsg) {
            msg = o.createOmi("msg", doc);
            msg.setAttribute("xmlns", "odf.xsd");
            requestElem = o.evaluateXPath(doc, "/omi:omiEnvelope/*")[0];
            if (requestElem != null) {
              requestElem.appendChild(msg);
              my.params.odf.update(currentParams.odf);
            } else {
              console.log("ERROR: No request found");
              return;
            }
          } else {
            msg = o.evaluateXPath(doc, "/omi:omiEnvelope/*/omi:msg");
            for (i = 0, len = msg.length; i < len; i++) {
              m = msg[i];
              m.parentElement.removeChild(m);
            }
          }
          return currentParams.msg = hasMsg;
        }
      }
    };
    my.generate = function() {
      return WebOmi.formLogic.setRequest(currentParams.requestDoc);
    };
    my.forceGenerate = function(useOldDoc) {
      var cp, key, o, ref, results, updateFn;
      if (useOldDoc == null) {
        useOldDoc = false;
      }
      o = WebOmi.omi;
      cp = currentParams;
      if (!useOldDoc || (cp.requestDoc == null)) {
        cp.requestDoc = o.parseXml(my.xmls.template);
        cp.request = "empty";
      }
      if ((cp.request != null) && cp.request.length > 0 && (cp.ttl != null)) {
        ref = my.update;
        results = [];
        for (key in ref) {
          updateFn = ref[key];
          updateFn(cp[key]);
          results.push(my.generate());
        }
        return results;
      } else {

      }
    };
    my.forceLoadParams = function(omiRequestObject, useOldDoc) {
      var key, newVal, uiWidget;
      if (useOldDoc == null) {
        useOldDoc = false;
      }
      for (key in omiRequestObject) {
        newVal = omiRequestObject[key];
        uiWidget = WebOmi.consts.ui[key];
        if (uiWidget != null) {
          uiWidget.set(newVal);
        }
      }
      return my.forceGenerate(useOldDoc);
    };
    my.readAll = function(fastForward) {
      WebOmi.formLogic.setRequest(my.xmls.readAll);
      if (fastForward) {
        return WebOmi.formLogic.send(WebOmi.formLogic.buildOdfTreeStr);
      }
    };
    return WebOmi;
  };

  window.WebOmi = requestsExt(window.WebOmi || {});

}).call(this);
