//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:41:29 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "odf.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package parsing.xmlGen.odf;
