language: scala
scala:
  - "2.11.2"
notifications:
  flowdock: 8fa39d3ba829b0083c135134658d0ac2 fe0612eaf41017111bd1db99f1c00b49
branches:
  only:
    - master
    - development
    - travis
before_script:
  - cd "O-MI Node"
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - ln -s ../.git
  - sbt coveralls
  
