language: scala
scala:
  - "2.11.2"
notifications:
  flowdock: 8fa39d3ba829b0083c135134658d0ac2
branches:
  only:
    - master
    - development
    - travis
before_script:
  - cd "O-MI Node"
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt coveralls
  
