// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package parsing 
package xmlGen
package xmlTypes
import javax.xml.datatype.XMLGregorianCalendar

import scala.collection.immutable.{HashMap, Vector}

case class ObjectsType(ObjectValue: Seq[ObjectType] = Vector.empty,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val version: Option[String] = attributes.get("@version") map { _.as[String]}
}

      


case class ObjectType(id: Seq[QlmIDType] = Vector.empty,
  description: Seq[DescriptionType] = Vector.empty,
  InfoItem: Seq[InfoItemType] = Vector.empty,
  ObjectValue: Seq[ObjectType] = Vector.empty,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val typeValue: Option[String] = attributes.get("@type") map { _.as[String]}
}

      


case class InfoItemType(
  iname: Seq[QlmIDType] = Vector.empty,
  description: Seq[DescriptionType] = Vector.empty,
  MetaData: Seq[MetaDataType] = Vector.empty,
  value: Seq[ValueType] = Vector.empty,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val name: String = attributes("@name").as[String]
  lazy val typeValue: Option[String] = attributes.get("@type") map { _.as[String]}
}

      


case class MetaDataType(InfoItem: Seq[InfoItemType] = Vector.empty)
      


/** String with some"human-readable" text.
*/
case class DescriptionType(value: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val lang: Option[String] = attributes.get("@lang") map { _.as[String]}
}

      


case class QlmIDType(value: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val idType: Option[String] = attributes.get("@idType") map { _.as[String]}
  lazy val tagType: Option[String] = attributes.get("@tagType") map { _.as[String]}
  lazy val startDate: Option[XMLGregorianCalendar] = attributes.get("@startDate") map { _.as[javax.xml.datatype.XMLGregorianCalendar]}
  lazy val endDate: Option[XMLGregorianCalendar] = attributes.get("@endDate") map { _.as[javax.xml.datatype.XMLGregorianCalendar]}
}

      


case class ValueType(mixed: Seq[scalaxb.DataRecord[Any]] = Vector.empty,
  attributes: Map[String, scalaxb.DataRecord[Any]] = HashMap()) {
  lazy val typeValue: String = attributes("@type").as[String]
  lazy val dateTime: Option[XMLGregorianCalendar] = attributes.get("@dateTime") map { _.as[javax.xml.datatype.XMLGregorianCalendar]}
  lazy val unixTime: Option[Long] = attributes.get("@unixTime") map { _.as[Long]}
}

      

