// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package parsing
package xmlGen
package xmlTypes


/** Root element of Open Messaging Interface.
*/
case class OmiEnvelopeType(omienvelopetypeoption: scalaxb.DataRecord[xmlTypes.OmiEnvelopeTypeOption],
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[String]
  lazy val ttl = attributes("@ttl").as[Long]
}

      

trait OmiEnvelopeTypeOption

/** Payload for the protocol
*/
case class MsgType(mixed: Seq[scalaxb.DataRecord[Any]] = Nil)
      


/** Base type for "read", "write", "call" and "delete" requests.
*/
trait RequestBaseType {
  def nodeList: Option[xmlTypes.NodesType]
  def requestID: Seq[String]
  def msg: Option[xmlTypes.MsgType]
  def callback: Option[java.net.URI]
  def msgformat: Option[String]
  def targetType: xmlTypes.TargetTypeType
}

trait TargetTypeType

object TargetTypeType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding)(implicit fmt: scalaxb.XMLFormat[xmlTypes.TargetTypeType]): TargetTypeType = fmt.reads(scala.xml.Text(value), Nil) match {
    case Right(x: TargetTypeType) => x
    case x => throw new RuntimeException(s"fromString returned unexpected value $x for input $value")
  }
}

case object Device extends TargetTypeType { override def toString = "device" }
case object Node extends TargetTypeType { override def toString = "node" }


case class ReadRequestType(nodeList: Option[xmlTypes.NodesType] = None,
  requestID: Seq[String] = Nil,
  msg: Option[xmlTypes.MsgType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) extends RequestBaseType with OmiEnvelopeTypeOption {
  lazy val callback = attributes.get("@callback") map { _.as[java.net.URI]}
  lazy val msgformat = attributes.get("@msgformat") map { _.as[String]}
  lazy val targetType = attributes("@targetType").as[TargetTypeType]
  lazy val interval = attributes.get("@interval") map { _.as[String]}
  lazy val oldest = attributes.get("@oldest") map { _.as[BigInt]}
  lazy val begin = attributes.get("@begin") map { _.as[javax.xml.datatype.XMLGregorianCalendar]}
  lazy val end = attributes.get("@end") map { _.as[javax.xml.datatype.XMLGregorianCalendar]}
  lazy val newest = attributes.get("@newest") map { _.as[BigInt]}
  lazy val all = attributes.get("@all") map { _.as[Boolean]}
}

      


case class WriteRequestType(nodeList: Option[xmlTypes.NodesType] = None,
  requestID: Seq[String] = Nil,
  msg: Option[xmlTypes.MsgType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) extends RequestBaseType with OmiEnvelopeTypeOption {
  lazy val callback = attributes.get("@callback") map { _.as[java.net.URI]}
  lazy val msgformat = attributes.get("@msgformat") map { _.as[String]}
  lazy val targetType = attributes("@targetType").as[TargetTypeType]
}

      


/** List of results.
*/
case class ResponseListType(result: Seq[xmlTypes.RequestResultType] = Nil) extends OmiEnvelopeTypeOption
      


/** Call request type.
*/
case class CallRequestType(nodeList: Option[xmlTypes.NodesType] = None,
  requestID: Seq[String] = Nil,
  msg: Option[xmlTypes.MsgType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) extends RequestBaseType with OmiEnvelopeTypeOption {
  lazy val callback = attributes.get("@callback") map { _.as[java.net.URI]}
  lazy val msgformat = attributes.get("@msgformat") map { _.as[String]}
  lazy val targetType = attributes("@targetType").as[TargetTypeType]
}

      


/** Delete request type.
*/
case class DeleteRequestType(nodeList: Option[xmlTypes.NodesType] = None,
  requestID: Seq[String] = Nil,
  msg: Option[xmlTypes.MsgType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) extends RequestBaseType with OmiEnvelopeTypeOption {
  lazy val callback = attributes.get("@callback") map { _.as[java.net.URI]}
  lazy val msgformat = attributes.get("@msgformat") map { _.as[String]}
  lazy val targetType = attributes("@targetType").as[TargetTypeType]
}

      


/** Result of a request.
*/
case class RequestResultType(returnValue: xmlTypes.ReturnType,
  requestID: Seq[xmlTypes.IdType] = Nil,
  msg: Option[xmlTypes.MsgType] = None,
  nodeList: Option[xmlTypes.NodesType] = None,
  omiEnvelope: Option[xmlTypes.OmiEnvelopeType] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val msgformat = attributes.get("@msgformat") map { _.as[String]}
  lazy val targetType = attributes("@targetType").as[TargetTypeType]
}

      


/** Return status of request. Use HTTP codes / descriptions when applicable.
*/
case class ReturnType(value: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val returnCode = attributes("@returnCode").as[String]
  lazy val description = attributes.get("@description") flatMap { 
    case dr: scalaxb.DataRecord[Any] =>  
      dr.as[Option[String]]
  }
}

      


/** The nodesType is used anywhere in the schema where lists of nodes can appear. 
*/
case class NodesType(node: Seq[java.net.URI] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val typeValue = attributes.get("@type") map { _.as[String]}
}

      


/** Some kind of identifier with optional "format" attribute for indicating what kind of identifier is used. 
*/
case class IdType(value: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val format = attributes.get("@format") map { _.as[String]}
}

      


case class CancelRequestType(nodeList: Option[xmlTypes.NodesType] = None,
  requestID: Seq[xmlTypes.IdType] = Nil) extends OmiEnvelopeTypeOption
      

